# studiekeuze123_all_20200417.xlsx columns to be dropped
drop_studiekeuze_cols = ['IndicatieIntensiefProgramma', 
             'SelectieEisenIntensiefProgramma', 
             'VerhoogdCollegegeldIntensiefProgramma', 
             'BezoekadresStraat', 
             'BezoekadresNummer', 
             'BezoekadresPostcode', 
             'Bekostiging', 'AssociateDegree', 'JointDegree',
             'BSAopmerking', 'Studielast',
             'AlgemeenOordeel', 
             'SourceURL', # soms URL gevuld --> mogelijk nieuwe bronnen ?
             "TitelHodex", 
             "Afstandonderwijs", 
             "Avondonderwijs", 
             "HeeftBindendStudieAdvies", 
             "HeeftExtraInstroommoment",
             "ExtraStudiekosten", 
             "LangeBeschrijvingOpleiding", 
             "Opleidingswebsite", 
             "PercentageStudentenNaarBuitenland",
             "PercentageStudentenUitBuitenland", # mogelijk interessant voor techstudies ?
             "PercentageDocentenUitBuitenland",
             "PercentageDocentenNaarBuitenland",
             "PercentageAfstandsonderwijs",
             "PercentageAvondonderwijs",
             "WerkgroepGrootte",
             "IsKoepelOpleiding",
             "StudiekeuzecheckNaam",
             "StudiekeuzecheckBeleidVoor1Mei", "StudiekeuzecheckBeleidNa1Mei",
             "StudiekeuzecheckVerplicht", "StudiekeuzecheckUrl", "StudiekeuzecheckOmschrijving",
             "HeeftHonoursProgramma", "InstroomVoltijd", "InstroomDeeltijd", "InstroomDuaal", 
             "InstroomTotaal", "InstroomMan", "InstroomVrouw",
             "AantalStudentenVoltijd", "AantalStudentenDuaal", "AantalStudentenTotaal",
             "PercentageMannelijkeStudenten", "PercentageVrouwelijkeStudenten",
             'AlgemeenOordeel01Wx', 'nAlgemeenOordeel01', 'AlgemeenOordeel01aWPrc',
             'AlgemeenOordeel01bWPrc', 'AlgemeenOordeel01cWPrc',
             'AlgemeenOordeel01dWPrc', 'AlgemeenOordeel01eWPrc',
             'ContacttijdEersteJaarVoltijd', 'ContacttijdEerstejaarsVoltijdAantal',
             'WettelijkeVooropleidingseisenVwo',
             'OpmerkingenBijWettelijkeVooropleidingseisenVwo',
             'WettelijkeAanvullendeEisenVwo', 'WettelijkeVooropleidingseisenHavo',
             'OpmerkingenBijWettelijkeVooropleidingseisenHavo',
             'WettelijkeAanvullendeEisenHavo', 'ToelatingsEisenMbo',
             'ToelatingseisenHboWoBachelor', 'maxjaar1CIJFHO',
             'AfstandsonderwijsPrc', 'AvondonderwijsPrc', 'NSEEnqueteJaar'
            ]
